# Generated by Django 5.2 on 2025-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de imagen')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='Cantidad')),
                ('source', models.CharField(default='D1', max_length=50, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
